### ISSUE TITLE
Aggiornamento ad API 2.0

### ISSUE THREAD

**Issue by ccxx72** [Gianbacchio/ESP8266-TelegramBot#3]
E' previsto ? Non riesco piu' a ricevere risposta dal bot nonostante veda sul monitor seriale che il messaggio arriva.

**Comment by Gianbacchio** [comment]
Ciao,
devo verificare che cosa è cambiato.
sicuramente lo aggiornerò a breve.

**Comment by ccxx72** [comment]
Grazie per la risposta.
Vorrei chiederti se ti fosse possibile poi scrivere anche sinteticamente cosa e' cambiato e come hai rimediato.
